services:
  backend:
    build: ./backend
    container_name: sicoob-api
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - sicoob_db:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sicoob_db:
